name: 'ipfs-backup'
description: 'Create a backup of your repository to IPFS for a full-proof backup'
author: 'Padmashree Jha (codewithpom)'
inputs:
  web3_token: # Get a token from https://web3.storage
    required: true
    description: "Your token from Web3.storage"
    
    
  folder:
    required: true
    description: "The folder in which the json file for the backup will be saved"
    default: "IPFS-backup"
runs:
  using: 'node16'
  main: 'dist/index.js'
